"""add github fields to users

Revision ID: 797d373e8242
Revises: d36b7edeba5e
Create Date: 2026-07-22 13:58:00.449164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797d373e8242'
down_revision: Union[str, Sequence[str], None] = 'd36b7edeba5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_access_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('github_avatar_url', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'users', ['github_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'github_avatar_url')
    op.drop_column('users', 'github_access_token')
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###
